In [1]:
import pandas as pd 
import numpy as np 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('covid_toy.csv')
df.sample(10)

    age  gender  fever   cough       city has_covid
37   55    Male  100.0    Mild    Kolkata        No
80   14  Female   99.0    Mild     Mumbai       Yes
49   44    Male  104.0    Mild     Mumbai        No
0    60    Male  103.0    Mild    Kolkata        No
63   10    Male  100.0    Mild  Bangalore        No
92   82  Female  102.0  Strong    Kolkata        No
34   74    Male  102.0    Mild     Mumbai       Yes
86   25    Male  104.0    Mild  Bangalore       Yes
72   83  Female  101.0    Mild    Kolkata        No
10   75  Female    NaN    Mild      Delhi        No

In [3]:
df['fever'].value_counts()

fever
101.0    17
98.0     17
104.0    14
100.0    13
99.0     10
102.0    10
103.0     9
Name: count, dtype: int64

In [4]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [5]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
xtrain, xtest, ytrain, ytest = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],train_size=0.3)

In [8]:
xtrain

    age  gender  fever   cough       city
16   69  Female  103.0    Mild    Kolkata
55   81  Female  101.0    Mild     Mumbai
52   47  Female  100.0  Strong  Bangalore
90   59  Female   99.0  Strong      Delhi
0    60    Male  103.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
93   27    Male  100.0    Mild    Kolkata
89   46    Male  103.0  Strong  Bangalore
6    14    Male  101.0  Strong  Bangalore
1    27    Male  100.0    Mild      Delhi
8    19  Female  100.0  Strong  Bangalore
79   48  Female  103.0    Mild    Kolkata
80   14  Female   99.0    Mild     Mumbai
68   54  Female  104.0  Strong    Kolkata
48   66    Male   99.0  Strong  Bangalore
54   60  Female   99.0    Mild     Mumbai
36   38  Female  101.0    Mild  Bangalore
28   16    Male  104.0    Mild    Kolkata
21   73    Male   98.0    Mild  Bangalore
35   82  Female  102.0  Strong  Bangalore
37   55    Male  100.0    Mild    Kolkata
50   19    Male  101.0    Mild      Delhi
58   23    Male   98.0  Strong     Mumbai
4    65  Female  101.0    Mild     Mumbai
99   10  Female   98.0  Strong    Kolkata
33   26  Female   98.0    Mild    Kolkata
65   69  Female  102.0    Mild  Bangalore
49   44    Male  104.0    Mild     Mumbai
85   16  Female  103.0    Mild  Bangalore
43   22  Female   99.0    Mild  Bangalore

In [9]:
ytrain

16    Yes
55    Yes
52    Yes
90     No
0      No
42    Yes
93    Yes
89     No
6      No
1     Yes
8      No
79    Yes
80    Yes
68     No
48     No
54    Yes
36     No
28     No
21    Yes
35     No
37     No
50    Yes
58    Yes
4      No
99    Yes
33     No
65     No
49     No
85    Yes
43    Yes
Name: has_covid, dtype: object

In [10]:
from sklearn.compose import ColumnTransformer

In [11]:
transformer = ColumnTransformer(transformers=[
    ('tn1', SimpleImputer(), ['fever']),
    ('tn2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tn3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
], remainder='passthrough')

In [12]:
transformer.fit_transform(xtrain).shape

(30, 7)