In [1]:
import pandas as pd  
import numpy as np

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

### Worling with dates

In [7]:
# convet datetime dataype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### extract year

In [10]:
date['date_year']= date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### extract months

In [12]:
date['date_month']= date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [13]:
date['date_monthname']= date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_monthname
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [14]:
date['day']= date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_monthname,day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [15]:
date['day_name']= date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_monthname,day,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

### is it weekend

In [17]:
date['day_is_Weekend']= np.where(date['day_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_monthname,day,day_name,day_is_Weekend
0,2019-12-10,2019,12,December,10,Tuesday,0
1,2018-08-15,2018,8,August,15,Wednesday,0
2,2018-10-23,2018,10,October,23,Tuesday,0
3,2019-08-17,2019,8,August,17,Saturday,1
4,2019-01-06,2019,1,January,6,Sunday,1

### Extract week of the year

In [38]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_monthname,day,day_name,day_is_Weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1,1

### Extract time elasped btw dates

In [43]:
import datetime 
today = datetime.datetime.today()
today

datetime.datetime(2025, 5, 31, 12, 35, 9, 748398)

In [45]:
today - date['date']

0     1999 days 12:35:09.748398
1     2481 days 12:35:09.748398
2     2412 days 12:35:09.748398
3     2114 days 12:35:09.748398
4     2337 days 12:35:09.748398
                 ...
995   2427 days 12:35:09.748398
996   2368 days 12:35:09.748398
997   2216 days 12:35:09.748398
998   2281 days 12:35:09.748398
999   2055 days 12:35:09.748398
Name: date, Length: 1000, dtype: timedelta64[ns]

## time

In [48]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [62]:
time['date'] = pd.to_datetime(time['date'])

time['hour'] = time['date'].dt.hour
time['min']  = time['date'].dt.minute
time['sec']  = time['date'].dt.second
time.head()

,date,msg,time,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013-12-15 00:50:00,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014-04-29 23:40:00,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012-12-30 00:21:00,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014-11-28 00:31:00,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013-10-26 23:11:00,23,11,0